browser=chrome
url=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
username=Admin
password=admin123
baseUrl=https://jsonplaceholder.typicode.com
apiKey=free_user_3FcrEm0MNkUJEpHVX96FIpkhy4x